# Generated by Django 3.1.7 on 2021-03-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0002_auto_20210312_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
