# Generated by Django 3.1.6 on 2021-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210215_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='service_category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('gifting', 'gifting')], default='clothing', max_length=20),
        ),
    ]
