# Generated by Django 3.1.6 on 2021-02-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210215_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='service_category',
        ),
    ]
