# Generated by Django 3.1.7 on 2021-03-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, default=None, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True)),
                ('refer_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('preferred_contact', models.CharField(max_length=100, null=True)),
                ('referral_code', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='orders.customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem_Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=None, max_length=700, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='User-Images/%Y/%m/%d')),
                ('expected_by', models.CharField(default=None, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_gifts', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_gifts', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceS', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priceXL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priceXXL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantityS', models.PositiveIntegerField(default=1, null=True)),
                ('quantityM', models.PositiveIntegerField(default=1, null=True)),
                ('quantityL', models.PositiveIntegerField(default=1, null=True)),
                ('quantityXL', models.PositiveIntegerField(default=1, null=True)),
                ('quantityXXL', models.PositiveIntegerField(default=1, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
