# Generated by Django 3.1.7 on 2021-03-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0004_auto_20210313_1331'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem_gifts',
            name='variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='gifting.variants'),
        ),
        migrations.AlterField(
            model_name='orderitem_gifts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_gifts', to='gifting.productgifting'),
        ),
    ]
