# Generated by Django 3.1.7 on 2021-03-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0004_auto_20210313_1331'),
        ('orders', '0003_auto_20210314_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem_gifts',
            name='variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='gifting.variants'),
        ),
    ]
