# Generated by Django 3.1.7 on 2021-03-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210314_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem_bulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=None, max_length=700, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('expected_by', models.CharField(default=None, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk', to='orders.order')),
            ],
        ),
    ]
