# Generated by Django 3.1.7 on 2021-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_bulk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem_bulk',
            name='color',
        ),
    ]
