# Generated by Django 3.1.7 on 2021-03-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0006_remove_orderitem_bulk_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem_bulk',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_bulk', to='shop.product'),
        ),
    ]
