# Generated by Django 3.1.7 on 2021-03-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_bulk_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_ten_count',
            field=models.IntegerField(default=0),
        ),
    ]
