# Generated by Django 3.1.7 on 2021-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
