# Generated by Django 3.1.7 on 2021-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210318_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
