# Generated by Django 3.1.7 on 2021-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210320_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
