# Generated by Django 3.1.7 on 2021-03-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210325_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reffered_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
    ]
